# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_auto_20170908_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_date',
            new_name='update_time',
        ),
    ]
