# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='phone address')),
                ('user_type', models.CharField(blank=True, choices=[('gamer', '玩家'), ('doctor', '医生')], max_length=6)),
                ('name', models.CharField(blank=True, max_length=10)),
                ('sex', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('secret', '保密')], max_length=6)),
                ('team', models.CharField(blank=True, max_length=255)),
                ('game', models.CharField(blank=True, default=None, max_length=140, null=True)),
                ('job', models.CharField(blank=True, max_length=140)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
