# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170907_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='classify',
            field=models.CharField(blank=True, choices=[('FCK', '妇产科'), ('MNWK', '泌尿外科'), ('PFK', '皮肤科'), ('GK', '骨科'), ('NFMK', '内分泌科'), ('XXGNK', '心血管内科'), ('SJK', '神经科'), ('XHNK', '消化内科'), ('SZNK', '肾脏内科'), ('YJK', '药剂科'), ('JJK', '急诊科'), ('YK', '眼科'), ('JSXLK', '精神心理科'), ('ZLK', '肿瘤科'), ('EBYHK', '耳鼻咽喉科'), ('FSK', '风湿科'), ('QK', '全科'), ('KQK', '口腔科'), ('HXK', '呼吸科'), ('PTWK', '普通外科'), ('XXWK', '心胸外科'), ('NWK', '脑外科'), ('GDYXWK', '肝胆胰腺外科'), ('CWGCWK', '肠胃肛肠外科'), ('RXWK', '乳腺外科'), ('XYK', '血液科'), ('YXJYK', '影像检验科'), ('GRCRK', '感染传染科'), ('TTMZK', '疼痛&麻醉科')], max_length=30, verbose_name='医生类别'),
        ),
    ]
